name: Build and Release Electron App

run-name: 📦 Build Multiplataforma ${{ github.ref_name }}

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Se ejecuta automáticamente cuando creas un tag como v1.0.2

  workflow_dispatch:
    inputs:
      os:
        description: 'Run build on a specific runner (or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - windows-latest
          - macos-latest
          - ubuntu-latest

permissions:
  contents: write  # Necesario para crear Releases y subir instaladores

env:
  DEBUG: electron-builder

jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      max-parallel: 1

      matrix:
        os: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.os != 'all') && fromJson(format('["{0}"]', github.event.inputs.os)) || fromJson('["windows-latest","macos-latest","ubuntu-latest"]') }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias del sistema (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 ruby ruby-dev build-essential rpm dpkg libarchive-tools
          sudo gem install --no-document fpm

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Construir y Publicar (Windows)
        if: runner.os == 'Windows'
        run: npm run release:win

      - name: Construir y Publicar (macOS)
        if: runner.os == 'macOS'
        run: npm run release:mac

      - name: Construir y Publicar (Linux)
        if: runner.os == 'Linux'
        env:
          USE_SYSTEM_FPM: "true"
        run: npm run release:linux
